# template ispired from  https://peterhpchen.github.io/VuejsQuest/
# 
language: node_js

node_js:
  - "10"
script:
  - yarn install
  - yarn :build

# deploy:
#   provider: pages
#   skip-cleanup: true
#   local_dir: docs/.vuepress/dist
#   github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
#   keep-history: true
#   on:
#     branch: master

notifications:
  slack: 
    rooms:
	    - ci-v:re7m5a8P6q5rP4XwfpGu7qU0#general
	    - ci-v:re7m5a8P6q5rP4XwfpGu7qU0#random
    on_success: change # default: always